version: '3'
services:
  python:
    container_name: python
    image: riuzzo01/multi-stage-app.py
    ports: 
     - "5000:5000"
    volumes:
      - /Desktop/nextcloud-1

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    ports:
      - "8081:80"
    volumes:
      - nextcloud:/var/www/html
  
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes: 
  db:
  nextcloud: 
 

