version: '3'
services:
  python:
    container_name: python
    image: riuzzo01/multi-stage-app-python-alpine
    ports: 
     - "5000:5000"
    volumes:
      - /Desktop/nextcloud-1
    networks:
      - backend

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    ports:
      - "8081:80"
    volumes:
      - nextcloud:/var/www/html
    networks:
      - backend
  
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes: 
  db:
  nextcloud: 

networks:
  backend:
    driver: bridge
 

